### ISSUE TITLE
Play store açıklamasında küçük yazım hatası

### ISSUE THREAD

**Issue by yusuf0x73** [turkiasoft/HizliSu.Mobile#2]
Play store açıklamasında küçük yazım hatası var.

"derdidne" yerine "derdinde" yazılması gerek.

**Comment by CodeOutput** [comment]
bilgilendirme için tşkler

> Play store açıklamasında küçük yazım hatası var.
> 
> "derdidne" yerine "derdinde" yazılması gerek.
